# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
