# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_branch_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location_address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
