# Generated by Django 2.2.7 on 2019-11-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0003_branch_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='location_address',
        ),
    ]
